name: Run Docker buildx
env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        TAG_FMT: '^refs/tags/(((.?[0-9]+){3,4}))$'

on:
        push:
                tags: [ '*' ]

jobs:
        build:
                runs-on: ubuntu-18.04
                name: Build umbrel middleware
                steps:
                        - name: setup environment
                          run: |
                                  if ! echo "$GITHUB_REF" | grep -qE "$TAG_FMT"; then
                                        echo "ERR: TAG must be in format: vX.Y.Z[.P][-VARIANT]+build<N>"
                                        exit 1
                                  fi
                                  VERSION="$(echo "$GITHUB_REF" | sed -E "s|$TAG_FMT|\2|")"
                                  
                                  TAG="$(echo "$GITHUB_REF" | sed -E "s|$TAG_FMT|\1|")"
                                  echo ::set-env name=TAG::"$TAG"
                                  
                        - name: Debug
                          run: |
                                  printf "    TAG: %s\n"  "$TAG"                                  
                        - name: Login to Docker for building
                          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "nolim1t" --password-stdin
                        - name: Checkout project
                          uses: actions/checkout@v2
                        - name: setup buildx
                          uses: crazy-max/ghaction-docker-buildx@v1
                          id: buildx
                          with:
                                  buildx-version: latest
                                  qemu-version: latest
                        - name: Available platforms
                          run: echo ${{ steps.buildx.outputs.platforms }}
                        - name: Run buildx
                          run: |
                                  docker buildx build \
                                  --platform linux/amd64,linux/arm/v7,linux/arm64 \
                                  --target nolim1t/umbrel-middleware:$TAG \
                                  --output "type=registry" \
                                  .
                        - name: List all images
                          run: docker images

